config/routes.rb
Rails.application.routes.draw do
  resources :elections

end

app/models/election.rb
class Election < ActiveRecord::Base
  validates :name, :occurs_on, :published_on, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :set_election, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /elections
  # GET /elections.json
  def index
    @elections = Election.all
  end

  # GET /elections/1
  # GET /elections/1.json
  def show
  end

  # GET /elections/new
  def new
    @election = Election.new
  end

  # GET /elections/1/edit
  def edit
  end

  # POST /elections
  # POST /elections.json
  def create
    @election = Election.new(election_params)
    @election.save
    respond_with @election
  end

  # PATCH/PUT /elections/1
  # PATCH/PUT /elections/1.json
  def update
    @election.update(election_params)
    respond_with(@election)
  end

  # DELETE /elections/1
  # DELETE /elections/1.json
  def destroy
    @election.destroy
    respond_to do |format|
      format.html { redirect_to elections_url, notice: 'Election was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_election
      @election = Election.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def election_params
      params.require(:election).permit(:name, :occurs_on, :published_on, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/_form.html.erb
<%= form_for(@election) do |f| %>
  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@election.errors.count, "error") %> prohibited this election from being saved:</h2>

      <ul>
      <% @election.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :occurs_on %><br>
    <%= f.date_select :occurs_on %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elections/edit.html.erb
<h1>Editing election</h1>

<%= render 'form' %>

<%= link_to 'Show', @election %> |
<%= link_to 'Back', elections_path %>

app/views/elections/index.html.erb
<h1>Listing elections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Occurs on</th>
      <th>Published on</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elections.each do |election| %>
      <tr>
        <td><%= election.name %></td>
        <td><%= election.occurs_on %></td>
        <td><%= election.published_on %></td>
        <td><%= election.description %></td>
        <td><%= link_to 'Show', election %></td>
        <td><%= link_to 'Edit', edit_election_path(election) %></td>
        <td><%= link_to 'Destroy', election, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Election', new_election_path %>

app/views/elections/new.html.erb
<h1>New election</h1>

<%= render 'form' %>

<%= link_to 'Back', elections_path %>

app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @election.name %>
</p>

<p>
  <strong>Occurs on:</strong>
  <%= @election.occurs_on %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @election.published_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @election.description %>
</p>

<%= link_to 'Edit', edit_election_path(@election) %> |
<%= link_to 'Back', elections_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Harpoon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>